---
title: "Ticketing and Turnout: The Participatory Consequences of Low-Level Police Contact"

date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  bookdown::pdf_document2:
    toc: no
    fig_caption: yes
    latex_engine: xelatex
    keep_tex: true
bibliography: "policing_turnout.bib"
link-citations: yes
fontsize: 12pt
header-includes:
    - \usepackage{rotating}
    - \usepackage{setspace}
---

\pagenumbering{gobble}
\pagebreak
```{r setup, echo = F, message = F, warning = F}
library(ragg)
library(systemfit)
library(ggpubr)
library(tidyverse)
library(kableExtra)
library(data.table)
ragg_png = function(..., res = 300) {
  ragg::agg_png(..., res = res, units = "in")
}
knitr::opts_chunk$set(dev = "ragg_png", dpi = 800)
knitr::opts_knit$set(root.dir = "..", dev = "cairo_pdf")
```
\pagenumbering{arabic}
\doublespacing

```{r did-different-approaches, echo = FALSE, message = F, warning = F, fig.width = 7.5, fig.height = 6, fig.cap = "\\label{fig:did-1}Effect of Being Ticketed on Turnout (no matching at all)", fig.pos = "H", fig.align = "center"}
p2 <- readRDS("temp/ts.rds")
print(p2)
```


```{r coef-plot-primary, echo = FALSE, message = F, warning = F, fig.width = 7.5, fig.height = 8, fig.cap = "\\label{fig:did-1}Effect of Being Ticketed on Turnout", fig.pos = "H", fig.align = "center"}
p2 <- readRDS("temp/coef_plot.rds")
print(p2)
```

```{r windows, echo = FALSE, message = F, warning = F, fig.width = 7.5, fig.height = 5, fig.cap = "\\label{fig:did-1}Black Relative", fig.pos = "H", fig.align = "center"}
p2 <- readRDS("temp/window_plot_good.rds")
print(p2)
```

```{r event-study-primary, echo = FALSE, message = F, warning = F, fig.width = 7.5, fig.height = 4, fig.cap = "\\label{fig:did-1}Effect of Being Ticketed on Turnout", fig.pos = "H", fig.align = "center"}
p2 <- readRDS("temp/event_study.rds")
print(p2)
```





